development:
  #<<: *default
  #database: GestionMaestria_development
  adapter: postgresql
  encoding: utf8
  database: GestionMaestria_development
  pool: 5
  username: postgres
  password: 123

test:
  #<<: *default
  adapter: postgresql
  encoding: utf8
  database: GestionMaestria_test
  username: postgres
  password: 123

#
production:
  adapter: postgresql
  encoding: utf8
  database: GestionMaestria_development
  pool: 5
  username: 
  password: 
