development:
  adapter: postgresql
  encoding: utf8
  database: gestion_curricular
  pool: 5
  username: postgres
  password: 1qa2ws3ed

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: gestion_test
  username: postgres
  password: 1qa2ws3ed

production:
  adapter: postgresql
  encoding: utf8
  database: project_production
  pool: 5
  username:
  password:

cucumber:
  <<: *TEST
